### PR TITLE
Simplify the Ansible groups

### PR DESCRIPTION
**Pull request by adborden**
We'll remap to the right groups within the Ansible inventory (hosts file).

### CODE REVIEW

**Comment by mogul** [comment]
@adborden says we're waiting on a change in `datagov-deploy` to be finalized before we can take this one out of draft state. Aaron, can you link that other PR here when you get a chance?

**Comment by mogul** [comment]
@adborden we didn't link to the other PR... Should this still be in draft state?

**Comment by mogul** [comment]
@adborden are these changes still relevant giving the broader reorganization you've done this week?

**Comment by adborden** [comment]
Right, moved to a static inventory in https://github.com/GSA/datagov-deploy/pull/2004 so these ansible group tags are no longer applicable.

**Pull request closed without merging**
