### PR TITLE
Remove Sai

### PR DESCRIPTION
**Pull request by mogul**
Merge after CircleCI shows that this does the right thing in the `plan` step.

### CODE REVIEW

**Comment by mogul** [comment]
This isn't what I expected to see in CircleCI at all! @adborden any idea what's up here?

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  + module.ckan_cloud.module.vpc.module.vpc.aws_nat_gateway.this
      id:                   <computed>
      allocation_id:        "eipalloc-0561c62b1a0fd78e6"
      network_interface_id: <computed>
      private_ip:           <computed>
      public_ip:            <computed>
      subnet_id:            "subnet-0c6d9fdca741a769d"
      tags.%:               "3"
      tags.Name:            "ckan-cloud-ckan-cloud-dev-us-east-1c"
      tags.Terraform:       "true"
      tags.env:             "ckan-cloud-dev"

  ~ module.ckan_cloud.module.vpc.module.vpc.aws_route.private_nat_gateway
      nat_gateway_id:       "nat-0b6b3e254c48126b2" => "${element(aws_nat_gateway.this.*.id, count.index)}"


Plan: 1 to add, 1 to change, 0 to destroy.
```

**Comment by mogul** [comment]
Leaving draft until https://github.com/GSA/datagov-infrastructure-live/pull/54 is merged

**Comment by adborden** [comment]
Chatted with @mogul but wanted to document this for others. As part of #54 , I had `terraform import`'d  the IAM policy too early, so the policy was now part of the terraform state even though the PR had not yet been merged. The `import` needs to happen _before_ the merge, but really it should happen immediately before, not when I created the PR. Anyway, the "fix" is to merge #54 before merging anything else.

Some followup conversation in [slack](https://gsa-tts.slack.com/archives/C2N85536E/p1586553619271500).

**Comment by adborden** [comment]
.. and now it looks like I removed some essential permissions for ckan-cloud-dev in #54 :confused:

**Comment by mogul** [comment]
This why we review, celebrate that we caught it!

**Comment by adborden** [comment]
```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # module.saiabhisaikgoud_udthawar.aws_iam_user.default will be destroyed
  - resource "aws_iam_user" "default" {
      - arn           = "arn:aws:iam::587807691409:user/saiabhisaikgoud.udthawar@gsa.gov" -> null
      - force_destroy = true -> null
      - id            = "saiabhisaikgoud.udthawar@gsa.gov" -> null
      - name          = "saiabhisaikgoud.udthawar@gsa.gov" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDAYRXARSKIWHRMMU2BD" -> null
    }

  # module.saiabhisaikgoud_udthawar.aws_iam_user_group_membership.default will be destroyed
  - resource "aws_iam_user_group_membership" "default" {
      - groups = [
          - "developers",
        ] -> null
      - id     = "terraform-20200403135416083500000001" -> null
      - user   = "saiabhisaikgoud.udthawar@gsa.gov" -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.

------------------------------------------------------------------------
```

**Pull request merged**
