### PR TITLE
Phase I transition to terraform v0.12

### PR DESCRIPTION
**Pull request by adborden**
Part of #2 #3 #27

This is the first phase of dropping Terragrunt and upgrading to Terraform
v0.12. This replaces the `ci` and `bionic` environments with a new `sandbox`
environment. The old `bionic` and `ci` environments can be removed in Phase II.

## What's left?

This PR should be merged, but there are some remaining issues that will follow
in Phase II:

- add sandbox-validate and sandbox-plan as a required CI checks
- destroy `bionic` and `ci` environments
- update the docs for terraform versions
- create `sandbox` Ansible inventory based on `ci`
- delete `bionic` and `ci` environments
- merge [datagov-infrastructure-modules/feature-terraform-12](https://github.com/GSA/datagov-infrastructure-modules/tree/feature-terraform-12) with a major version bump (https://github.com/GSA/datagov-infrastructure-modules/pull/45)
- update `source` references to new `datagov-infrastructure-modules` version

### CODE REVIEW

**Comment by mogul** [comment]
The code changes look OK though I'm unsure how to validate them... Just having the CircleCI pipeline pass?

**Comment by adborden** [comment]
Yeah, CI should do the validation... Hrmm I don't know why I didn't add sandbox-plan and sandbox-apply. Would be helpful to see the plan.

**Comment by adborden** [comment]
Nm, the plan was in there. Still a few fixes to make.

**Comment by adborden** [comment]
https://app.circleci.com/pipelines/github/GSA/datagov-infrastructure-live/162/workflows/0a4f4de5-4668-46b7-845e-4aad65d1a572/jobs/799

Plan: 135 to add, 0 to change, 0 to destroy.

**Pull request merged**
